=== AntonioModer/libbehavior/trunk/Snow Leopard/Snow Leopard/Resources/XML/SLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://code.google.com/p/snow-leopard/" elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://code.google.com/p/snow-leopard/">

  <xs:attributeGroup name="std">
    <xs:attribute name="description" type="xs:string" default=""/>
    <xs:attribute name="id" type="xs:string"/>
    <xs:attribute name="name" type="xs:string" default="NoName"/>
  </xs:attributeGroup>

  

  <xs:attributeGroup name="position">
    <xs:attribute name="xPosition" type="xs:double" default="0"/>
    <xs:attribute name="yPosition" type="xs:double" default="0"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="capacitors">
    <xs:attribute name="capacitor_type" type="Capacitor_Type"/>
    <xs:attribute name="capacitor_amount" type="xs:integer" default="0"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="missile_ammo">
    <xs:attribute name="missile_ammo_type" type="Missile_Ammo_Type" default="Incendiary Missile"/>
    <xs:attribute name="missile_ammo_amount" type="xs:integer" default="0"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="gun_ammo">
    <xs:attribute name="gun_ammo_type" type="Gun_Ammo_Type" default="Lead rounds"/>
    <xs:attribute name="gun_ammo_amount" type="xs:integer" default="0"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="image">
    <xs:attribute name="pictureSource" type="xs:string"/>
    <xs:attribute name="scale" type="xs:integer" default="20"/> <!--in meters per pixel-->
    <xs:attribute name="base_angle" type="xs:integer" default="0"/>
    <xs:attribute name="current_angle" type="xs:integer" default="0"/>
    <xs:attribute name="translation_origin" type="Origin_Type" default="center"/>
    <xs:attribute name="rotation_origin" type="Origin_Type" default="center"/>
    <xs:attribute name="translation_offset_x" type="xs:integer" default="0"/>
    <xs:attribute name="translation_offset_y" type="xs:integer" default="0"/>
    <xs:attribute name="rotation_offset_x" type="xs:integer" default="0"/>
    <xs:attribute name="rotation_offset_y" type="xs:integer" default="0"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="movement">
    <xs:attribute name="movementHeading" type="xs:integer" default="0"/>
    <xs:attribute name ="movementSpeed" type ="xs:integer" default="0"/>
    <xs:attribute name ="accelerationMagnitude" type="xs:integer" default="0"/>
    <xs:attribute name="accelerationHeading" type="xs:integer" default="0"/>
  </xs:attributeGroup>

  <xs:attribute name="recharge_time" type="xs:integer" default="200"/>
  
  <xs:attributeGroup name="socket">
    <xs:attribute name="mass" type="Socket_Mass" default="20"/>
    <xs:attribute name="energy" type="Socket_Energy" default="20"/>
    <xs:attribute name="type" type="Socket_Type" default="Triangle"/>
  </xs:attributeGroup>

  <xs:attribute name="usesPhysics" type="xs:boolean" default="true"/>

  <xs:attributeGroup name="stdItem">
    <xs:attribute name="mass" type="xs:double" default="20"/>
    <xs:attribute name="energy_drain" type="xs:double" default="20"/>
    <xs:attribute name="reliability" type="xs:double" default="100"/>
    <xs:attribute name="HP" type="xs:double" default="100"/>
    <xs:attribute name="socket_type" type="xs:string" default="Triangle"/>
  </xs:attributeGroup>

  <xs:element name="WorldState">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Entity"/>
      </xs:sequence>
      <xs:attributeGroup ref="std"/>
      <xs:attribute name="time" type="xs:integer" default="0"/>
      <xs:attribute name="CoordinateSizeX" type="xs:double" default="1024"/> <!--in kilometers-->
      <xs:attribute name="CoordinateSizeY" type="xs:double" default="768"/>  <!--in kilometers-->
    </xs:complexType>
  </xs:element>
  <xs:element name="Entity">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" ref="BaseImage"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Socket"/>
      </xs:sequence>
      <xs:attributeGroup ref="std"/>
      <xs:attributeGroup ref="position"/>
      <xs:attributeGroup ref="movement"/>
      <xs:attribute name="isPlayer" type="xs:boolean" default="false"/>
      <xs:attribute name="faction" type ="xs:string" default="none"/>
      <xs:attribute ref="usesPhysics"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="BaseImage">
    <xs:complexType>
      <xs:attributeGroup ref="std"/>
      <xs:attributeGroup ref="image"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Socket">
    <xs:complexType>
      <xs:choice>
        <xs:element maxOccurs="1" ref="Beam_Weapon"/>
        <xs:element maxOccurs="1" ref="Gun_Weapon"/>
        <xs:element maxOccurs="1" ref="Missile_Weapon"/>
        <xs:element maxOccurs="1" ref="Device"/>
        <xs:element maxOccurs="1" ref="Engine"/>
        <xs:element maxOccurs="1" ref="Powerplant"/>
      </xs:choice>
      <xs:attributeGroup ref="std"/>
      <xs:attributeGroup ref="position"/>
      <xs:attributeGroup ref="socket"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Beam_Weapon">
    <xs:complexType>

      <xs:attributeGroup ref="std"/>
      <xs:attributeGroup ref="image"/>
      <xs:attributeGroup ref="capacitors"/>
      <xs:attributeGroup ref="movement"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Gun_Weapon">
    <xs:complexType>

      <xs:attributeGroup ref="std"/>
      <xs:attributeGroup ref="image"/>
      <xs:attribute name="subtype" type="Gun_Type" default="Machine Gun"/>
      <xs:attribute name="caliber" type="Gun_Caliber" default="5"/>
      <xs:attributeGroup ref="movement"/>
      <xs:attributeGroup ref="gun_ammo"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Missile_Weapon">
    <xs:complexType>

      <xs:attributeGroup ref="std"/>
      <xs:attributeGroup ref="image"/>
      <xs:attribute name="missile_size" type="Missile_Size" default="500"/>
      <xs:attribute name="multishot" type="Missile_Shot_Number" default="1"/>
      <xs:attributeGroup ref="missile_ammo"/>
      <xs:attributeGroup ref="movement"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Device">
    <xs:complexType>

      <xs:attributeGroup ref="std"/>
      <xs:attributeGroup ref="image"/>
      <xs:attributeGroup ref="movement"/>

      <xs:attribute name="subtype" type="Device_Type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Engine">
    <xs:complexType>

      <xs:attributeGroup ref="std"/>
      <xs:attributeGroup ref="image"/>
      <xs:attributeGroup ref="movement"/>

      <xs:attribute name="subtype" type="Engine_Type" default="Ion Thruster"/>

    </xs:complexType>
  </xs:element>
  <xs:element name="Powerplant">
    <xs:complexType>
      <xs:attributeGroup ref="std"/>
      <xs:attributeGroup ref="image"/>
      <xs:attribute name="subtype" type="Power_Type" default="Nuclear Fission Plant"/>
      <xs:attributeGroup ref="capacitors"/>
      <xs:attributeGroup ref="movement"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="General_Prefix">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Overvolted"/>
      <xs:enumeration value="High Quality"/>
      <xs:enumeration value="Reliable"/>
      <xs:enumeration value="Parallel"/>
      <xs:enumeration value="Cheap"/>
      <xs:enumeration value="Unreliable"/>
      <xs:enumeration value="Weak"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Size_Prefix">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Compact"/>
      <xs:enumeration value="Miniturized"/>
      <xs:enumeration value="Micro"/>
      <xs:enumeration value="Nano"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Engine_Type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Ion Thruster"/>
      <xs:enumeration value="Photon Thruster"/>
      <xs:enumeration value="Field Effect Drive"/>
      <xs:enumeration value="Quantum Effect Drive"/>
      <xs:enumeration value="Reactionless Drive"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Power_Type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Nuclear Fission Plant"/>
      <xs:enumeration value="Nuclear Fusion Plant"/>
      <xs:enumeration value="Partial Antimatter Annihilation Plant"/>
      <xs:enumeration value="Complete Antimatter Annihilation Plant"/>
      <xs:enumeration value="Zero Point Energy Extractor"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Device_Type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ECM"/>
      <xs:enumeration value="ECCM"/>
      <xs:enumeration value="Gravity Manipulator"/>
      <xs:enumeration value="Gravitational Field Stabilizer"/>
      <xs:enumeration value="Salvage Beam"/>
      <xs:enumeration value="Repair Bots"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Gun_Type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Machine Gun"/>
      <xs:enumeration value="Gauss Gun"/>
      <xs:enumeration value="Wide-angle gun"/>
      <xs:enumeration value="Machine wide-angle gun"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Missile_Ammo_Type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Incendiary Missile"/>
      <xs:enumeration value="Bio-Missile"/>
      <xs:enumeration value="Nanobot Missile"/>
      <xs:enumeration value="Piercing Missile"/>
      <xs:enumeration value="Towing Missile "/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Origin_Type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="top_left"/>
      <xs:enumeration value="top_center"/>
      <xs:enumeration value="top_right"/>
      <xs:enumeration value="center_left"/>
      <xs:enumeration value="center"/>
      <xs:enumeration value="center_right"/>
      <xs:enumeration value="bottom_left"/>
      <xs:enumeration value="bottom_center"/>
      <xs:enumeration value="bottom_right"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Gun_Caliber">
    <xs:restriction base="xs:integer">
      <xs:enumeration value="5"/>
      <xs:enumeration value="10"/>
      <xs:enumeration value="20"/>
      <xs:enumeration value="50"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Missile_Size">
    <xs:restriction base="xs:integer">
      <xs:enumeration value="50"/>
      <xs:enumeration value="100"/>
      <xs:enumeration value="200"/>
      <xs:enumeration value="500"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Missile_Shot_Number">
    <xs:restriction base="xs:integer">
      <xs:enumeration value="1"/>
      <xs:enumeration value="5"/>
      <xs:enumeration value="10"/>
      <xs:enumeration value="20"/>
      <xs:enumeration value="40"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Gun_Ammo_Type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Lead rounds"/>
      <xs:enumeration value="Depleted uranium rounds"/>
      <xs:enumeration value="Diamond rounds"/>
      <xs:enumeration value="Techtronium alloy rounds"/>
      <xs:enumeration value="Bio-warfare rounds"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Capacitor_Type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Ultracapacitor"/>
      <xs:enumeration value="Hypercapacitor"/>
      <xs:enumeration value="Nanocapacitor"/>
      <xs:enumeration value="Picocapacitor"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Socket_Mass">
    <!-- mega-->
    <xs:restriction base="xs:integer">
      <xs:enumeration value="5"/>
      <xs:enumeration value="10"/>
      <xs:enumeration value="20"/>
      <xs:enumeration value="50"/>
      <xs:enumeration value="100"/>
      <xs:enumeration value="200"/>
      <xs:enumeration value="500"/>
      <xs:enumeration value="1000"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Socket_Type">
    <!-- mega-->
    <xs:restriction base="xs:string">
      <xs:enumeration value="Triangle"/>
      <xs:enumeration value="Square"/>
      <xs:enumeration value="Pentagon"/>
      <xs:enumeration value="Hexagon"/>
      <xs:enumeration value="Octagon"/>
      <xs:enumeration value="Shell"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Socket_Energy">
    <!-- kilo-->
    <xs:restriction base="xs:integer">
      <xs:enumeration value="5"/>
      <xs:enumeration value="20"/>
      <xs:enumeration value="100"/>
      <xs:enumeration value="500"/>
      <xs:enumeration value="2000"/>
      <xs:enumeration value="5000"/>
      <xs:enumeration value="20000"/>
      <xs:enumeration value="100000"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Beam_Weapon_Type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Laser"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== AntonioModer/libbehavior/trunk/Snow Leopard/Snow Leopard/Resources/XML/example.xml
<WorldState id="1" description="ZOMG first worldstate" CoordinateSizeX="1024" CoordinateSizeY="768" name="hello world"  time="1"
            xmlns="http://code.google.com/p/snow-leopard/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://code.google.com/p/snow-leopard/ SLSchema.xsd" >
  <Entity xPosition="50" yPosition="100" name="Firefly" id="firefly" isPlayer="true"  description="transport hauler beloved by smugglers" >
    <BaseImage  pictureSource="resources\hulls\sample Hull.png" scale="20" id="fireflyimage"/>
    <Socket mass="10" energy="20" type="Triangle" xPosition="-30" yPosition="0" id="frontleftsocket">
      <Engine pictureSource="resources\hulls\sample Hull.png" scale="20" subtype="Photon Thruster" id="fireflyengine"/>
    </Socket>
  </Entity>

  <Entity xPosition="200" yPosition="100" name="Firefly" id="enemy" isPlayer="false"  description="transport hauler beloved by smugglers" >
    <BaseImage current_angle="90"  pictureSource="resources\hulls\sample Hull.png" scale="20" id="fireflyimage"/>
    <Socket mass="10" energy="20" type="Triangle" xPosition="-30" yPosition="0" id="frontleftsocket">
      <Engine pictureSource="resources\hulls\sample Hull.png" scale="20" subtype="Photon Thruster" id="fireflyengine"/>
    </Socket>
  </Entity>

  <Entity xPosition="530" yPosition="280" name="BackgroundImage" id="background">
    <BaseImage pictureSource="resources\backgrounds\background.png" scale="20" id="BackgroundImage"/>
  </Entity>
</WorldState>
